spring:
  security:
    user:
      roles: ${CONFIG_ROLES:manager}
      name: ${CONFIG_USERNAME:adminz}
      password: ${CONFIG_PASSWORD:123123zZ}
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka:
  client:
    register-with-euraka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  insteance:
    hostname: localhost
